#!/bin/sh
#

./scripts/config --file .config --disable  "AHCI"
./scripts/config --file .config --disable  "ANDROID_BOOT_IMAGE"
./scripts/config --file .config --enable   "ARM_SMCCC"
./scripts/config --file .config --disable  "ARM_SMCCC_FEATURES"
./scripts/config --file .config --set-val  "BOOTDELAY" "0"
./scripts/config --file .config --disable  "BOOTDEV_ETH"
./scripts/config --file .config --disable  "BOOTMETH_EXTLINUX"
./scripts/config --file .config --disable  "BOOTMETH_VBE"
./scripts/config --file .config --enable   "BOOT_RETRY"
./scripts/config --file .config --set-val  "BOOT_RETRY_TIME" "300"
./scripts/config --file .config --set-val  "BOOT_RETRY_MIN" "5"
./scripts/config --file .config --enable   "CMD_CONFIG"
./scripts/config --file .config --disable  "CMD_BOOTD"
./scripts/config --file .config --disable  "CMD_BOOTM"
./scripts/config --file .config --disable  "CMD_BOOTFLOW"
./scripts/config --file .config --disable  "CMD_HVC"
./scripts/config --file .config --enable   "CMD_PAUSE"
#./scripts/config --file .config --enable   "CMD_SATA"
./scripts/config --file .config --disable  "CMD_SCSI"
./scripts/config --file .config --enable   "CMD_SLEEP"
./scripts/config --file .config --disable  "CMD_SMC"
./scripts/config --file .config --disable  "EFI_LOADER"
./scripts/config --file .config --disable  "EXPO"
./scripts/config --file .config --set-str  "DEFAULT_FDT_FILE" "sun7i-a20-cubietruck.dtb"
./scripts/config --file .config --disable  "DISTRO_DEFAULTS"
./scripts/config --file .config --disable  "EFI_BOOTMGR"
./scripts/config --file .config --disable  "ENV_IS_IN_FAT"
./scripts/config --file .config --disable  "ISO_PARTITION"
./scripts/config --file .config --disable  "LEGACY_IMAGE_FORMAT"
./scripts/config --file .config --disable  "NETDEVICES"
./scripts/config --file .config --disable  "NET"
./scripts/config --file .config --enable   "NO_NET"
./scripts/config --file .config --disable  "PHYLIB"
./scripts/config --file .config --disable  "PHY_ADDR_ENABLE"
./scripts/config --file .config --disable  "PHY_REALTEK"
./scripts/config --file .config --set-str  "PREBOOT" ""
./scripts/config --file .config --enable   "RESET_TO_RETRY"
./scripts/config --file .config --disable  "SATA"
./scripts/config --file .config --disable  "SCSI_AHCI"
./scripts/config --file .config --disable  "SATA_CEVA"
./scripts/config --file .config --disable  "SCMI_FIRMWARE"
./scripts/config --file .config --disable  "SPL_FIRMWARE"
./scripts/config --file .config --disable  "SUPPORT_RAW_INITRD"
./scripts/config --file .config --disable  "SYSRESET_PSCI"
./scripts/config --file .config --disable  "USB"
./scripts/config --file .config --disable  "WDT_ARM_SMC"
